### ISSUE TITLE
Setup form isn't displayed when adding integrations

### ISSUE THREAD

**Issue by mKeRix** [YIO-Remote/integration.home-assistant#22]
## Description

When I open the web-configurator and want to add a new integration the setup dialog doesn't show for Home Assistant. This prevents me to setup the integration on the latest versions.

## How to Reproduce
1. Go to the web configurator integrations page.
2. Click on "Add Integration".
3. Select homeasssistant from the list.
4. Nothing is rendered.

## Expected behavior

I would expect the form with IP, Token etc. to show up.

## Your Environment

* Version used: 0.4.2
* Running on: 
  - YIO Remote
* Web Configurator: tested on 0.1.4 and 0.1.1

## Additional context

The relevant error in the logs seems to appear when the examples of one of the ssl booleans are rendered. `undefined` refers to the `examples` property:

```
TypeError: Cannot read property '0' of undefined
```

Downgrading to v0.4.1 fixes the issue.

**Comment by martonborzak** [comment]
I believe this was fixed in v0.4.4

**Comment by mKeRix** [comment]
Yep, just updated and it works fine now!
